apiVersion: apps/v1
kind: Deployment
metadata:
  name: booksstorage-mail-depl
spec:
  template:
    spec:
      containers:
        - name: booksstorage-mail
          resources:
            requests:
              memory: "100Mi"
              cpu: "200m"
            limits:
              memory: "500Mi"
              cpu: "600m"
