apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: booksstorage-argocd-dev
  namespace: argocd
spec:
  project: default
  sources:
    # Books-Storage
    - repoURL: https://github.com/Vininhos/Books-Storage.git
      targetRevision: HEAD
      path: K8s/BooksStorage/overlays/development

    # BooksStorage-Client
    - repoURL: https://github.com/Vininhos/Books-Storage.git
      targetRevision: HEAD
      path: K8s/BooksStorage-Client/overlays/development

    # BooksStorage-Feeder
    - repoURL: https://github.com/Vininhos/Books-Storage.git
      targetRevision: HEAD
      path: K8s/BooksStorage-Feeder/overlays/development

    # BooksStorage-Mail
    - repoURL: https://github.com/Vininhos/Books-Storage.git
      targetRevision: HEAD
      path: K8s/BooksStorage-Mail/overlays/development

    # Elasticsearch
    - repoURL: https://github.com/Vininhos/Books-Storage.git
      targetRevision: HEAD
      path: K8s/Elasticsearch/overlays/development

    # Ingress
    - repoURL: https://github.com/Vininhos/Books-Storage.git
      targetRevision: HEAD
      path: K8s/Ingress/overlays/development

    # Kibana
    - repoURL: https://github.com/Vininhos/Books-Storage.git
      targetRevision: HEAD
      path: K8s/Kibana/overlays/development

    # Mailhog
    - repoURL: https://github.com/Vininhos/Books-Storage.git
      targetRevision: HEAD
      path: K8s/MailHog/overlays/development

    # Mongo
    - repoURL: https://github.com/Vininhos/Books-Storage.git
      targetRevision: HEAD
      path: K8s/Mongo/overlays/development

  destination:
    server: https://kubernetes.default.svc
    namespace: booksstorage-argocd-dev
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
