apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: booksstorage-argocd-prod
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/Vininhos/Books-Storage.git
      targetRevision: master

    # Books-Storage Application.
    - path: K8s/BooksStorage/overlays/prod
    - path: K8s/BooksStorage-Client/overlays/prod
    - path: K8s/BooksStorage-Feeder/overlays/prod
    - path: K8s/BooksStorage-Mail/overlays/prod

    # Infrastructure, observability and database.
    - path: K8s/Elasticsearch/overlays/prod
    - path: K8s/Ingress/overlays/prod
    - path: K8s/Kibana/overlays/prod
    - path: K8s/MailHog/overlays/prod
    - path: K8s/Mongo/overlays/prod

  destination:
    server: https://kubernetes.default.svc
    namespace: booksstorage-argocd-prod
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
