apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: booksstorage-argocd-dev
  namespace: argocd
spec:
  project: default
  sources:
    # Books-Storage Application.
    - repoURL: https://github.com/Vininhos/Books-Storage.git
      targetRevision: master
      path: K8s/BooksStorage/overlays/dev

    - repoURL: https://github.com/Vininhos/Books-Storage.git
      targetRevision: master
      path: K8s/BooksStorage-Client/overlays/dev

    - repoURL: https://github.com/Vininhos/Books-Storage.git
      targetRevision: master
      path: K8s/BooksStorage-Feeder/overlays/dev

    - repoURL: https://github.com/Vininhos/Books-Storage.git
      targetRevision: dotnet-legacy
      path: K8s/BooksStorage-Mail/overlays/dev

    # Infrastructure, observability and database.
    #    - repoURL: https://github.com/Vininhos/Books-Storage.git
    #  targetRevision: master
    #path: K8s/Elasticsearch/overlays/dev

    - repoURL: https://github.com/Vininhos/Books-Storage.git
      targetRevision: master
      path: K8s/Ingress/overlays/dev

    #- repoURL: https://github.com/Vininhos/Books-Storage.git
    #  targetRevision: master
    #  path: K8s/Kibana/overlays/dev

    - repoURL: https://github.com/Vininhos/Books-Storage.git
      targetRevision: master
      path: K8s/MailHog/overlays/dev

    - repoURL: https://github.com/Vininhos/Books-Storage.git
      targetRevision: master
      path: K8s/Mongo/overlays/dev

  destination:
    server: https://kubernetes.default.svc
    namespace: booksstorage-argocd-dev
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    #    automated:
    #  selfHeal: true
    #  prune: true
