apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: booksstorage-argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Vininhos/Books-Storage.git
    targetRevision: HEAD
    path: K8s/BooksStorage/overlays/development
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
