services:
  booksstorage:
    image: docker.io/viniciusrw/booksstorage:latest
    restart: always
    build:
      context: server/booksstorage
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - MONGODB_USERNAME=mongoadmin
      - MONGODB_PASSWORD=secret
      - MONGODB_DATABASE=bookstorage
      - MONGODB_COLLECTION=books
    depends_on:
      - mongodb

  mongodb:
    image: docker.io/mongo
    restart: always
    ports:
      - "27017:27017"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - ./mongo/data:/data/db

  booksstorageclient:
    image: docker.io/viniciusrw/booksstorageclient:latest
    restart: always
    build:
      context: client/
      dockerfile: Dockerfile
    ports:
      - "8078:80"
    deploy:
      mode: global

  booksstoragemail:
    image: docker.io/viniciusrw/booksstorage-mail:latest
    restart: always
    build:
      context: server/BooksStorage.Mail
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    deploy:
      mode: replicated
      replicas: 1

  mailhog:
    image: docker.io/mailhog/mailhog:latest
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"

  booksstorage-feeder:
    image: docker.io/viniciusrw/booksstorage-feeder:latest
    restart: always
    build:
      context: server/booksstorage-feeder
      dockerfile: Dockerfile
    environment:
      BOOKSSTORAGEAPIURL: http://booksstorage:8080/api/book
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - booksstorage
