services:
  booksstorage:
    image: viniciusrw/booksstorage:latest
    restart: always
    build:
      context: server/BooksStorage
      dockerfile: Dockerfile
    ports:
      - "8079:80"
    deploy:
      mode: replicated
      replicas: 1

  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - ./mongo/data:/data/db

  booksstorageclient:
    image: viniciusrw/booksstorageclient:latest
    restart: always
    build:
      context: client/
      dockerfile: Dockerfile
    ports:
      - "8078:80"
    deploy:
      mode: global

  booksstoragemail:
    image: viniciusrw/booksstorage-mail:latest
    restart: always
    build:
      context: server/BooksStorage.Mail
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    deploy:
      mode: replicated
      replicas: 1

  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"

  booksstorage-feeder:
    image: viniciusrw/booksstorage-feeder:latest
    restart: always
    build:
      context: server/booksstorage-feeder
      dockerfile: Dockerfile
    environment:
      BOOKSSTORAGEAPIURL: http://booksstorage/api/book
    deploy:
      mode: replicated
      replicas: 1
