version: '3'
services:
  booksstorage:
    image: viniciusrw/booksstorage:1.0.0
    restart: always
    build:
      dockerfile: /BooksStorage/Dockerfile
    ports:
      - "8080:80"
    deploy: 
      mode: replicated
      replicas: 1

  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    deploy: 
      mode: replicated
      replicas: 1
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - ~/mongo/data:/data/db
  
  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"
