apiVersion: apps/v1
kind: Deployment
metadata:
  name: booksstorage-client-depl
spec:
  template:
    spec:
      containers:
        - name: booksstorage-client
          resources:
            requests:
              memory: "200Mi"
              cpu: "100m"
            limits:
              memory: "500Mi"
              cpu: "500m"
