apiVersion: apps/v1
kind: Deployment
metadata:
  name: booksstoragefeeder-depl
spec:
  selector:
    matchLabels:
      app: booksstoragefeeder-depl
  template:
    metadata:
      labels:
        app: booksstoragefeeder-depl
    spec:
      containers:
        - name: booksstoragefeeder
          image:
