apiVersion: apps/v1
kind: Deployment
metadata:
  name: booksstoragefeeder-depl
spec:
  selector:
    matchLabels:
      app: booksstoragefeeder-depl
  template:
    metadata:
      labels:
        app: booksstoragefeeder-depl
    spec:
      containers:
      - name: booksstoragefeeder
        image: viniciusrw/booksstorage-feeder:1.0.2
        resources:
          requests:
            memory: "50Mi"
            cpu: "50m"
          limits:
            memory: "100Mi"
            cpu: "100m"
