apiVersion: apps/v1
kind: Deployment
metadata:
  name: booksstoragefeeder-depl
spec:
  selector:
    matchLabels:
      app: booksstoragefeeder-depl
  template:
    metadata:
      labels:
        app: booksstoragefeeder-depl
    spec:
      secureContext:
        runAsUser: 1000
        runAsGroup: 1000
      containers:
        - name: booksstoragefeeder
          image:
        securityContext:
          allowPrivilegeEscalation: false
