apiVersion: v1
kind: Service
metadata:
  name: mailhog
spec:
  selector:
    app: mailhog
  ports:
  - name: smtp-port
    port: 1025
    targetPort: smtp
  - name: http-port
    port: 8025
    targetPort: http