apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
spec:
  version: 8.12.0
  count: 1
  elasticsearchRef:
    name: elasticsearch
  http:
    service:
      spec:
        type: NodePort
        ports:
          - name: http
            nodePort: 30080
            port: 5601
            targetPort: 5601
            protocol: TCP
    tls:
      selfSignedCertificate:
        disabled: true
