apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "../../base"

patches:
  - path: "annotations.yaml"
    target:
      kind: Ingress
  - path: "ingressclassname.yaml"
    target:
      kind: Ingress