apiVersion: apps/v1
kind: Deployment
metadata:
  name: booksstorage-depl
spec:
  selector:
    matchLabels:
      app: booksstorage-depl
  template:
    metadata:
      labels:
        app: booksstorage-depl
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      containers:
        - name: booksstorage
          image:
          ports:
            - containerPort: 8080
              name: apiport
          securityContext:
            allowPrivilegeEscalation: false
