apiVersion: apps/v1
kind: Deployment
metadata:
  name: booksstorage-depl
spec:
  template:
    metadata:
      labels:
        app: booksstorage-depl
    spec:
      containers:
        - name: booksstorage
          image:
          ports:
            - containerPort: 8080
              name: apiport
