apiVersion: apps/v1
kind: Deployment
metadata:
  name: booksstorage-depl
spec:
  selector:
    matchLabels:
      app: booksstorage-depl
  template:
    metadata:
      labels:
        app: booksstorage-depl
    spec:
      containers:
      - name: booksstorage
        image: viniciusrw/booksstorage:1.0.7-k8s
        resources:
          limits:
            memory: "350Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
          name: apiport
