apiVersion: apps/v1
kind: Deployment
metadata:
  name: booksstoragefeeder
spec:
  selector:
    matchLabels:
      app: booksstoragefeeder
  template:
    metadata:
      labels:
        app: booksstoragefeeder
    spec:
      containers:
      - name: booksstoragefeeder
        image: viniciusrw/booksstorage-feeder:1.0.2
        resources:
          requests:
            memory: "128Mi"
            cpu: "200m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        env:
        - name: BOOKSSTORAGEAPIURL
          value: http://booksstorage-svc/api/book/email
