apiVersion: apps/v1
kind: Deployment
metadata:
  name: booksstorage-client-depl
  labels:
    app: booksstorage-client-depl
spec:
  selector:
    matchLabels:
      app: booksstorage-client-depl
  template:
    metadata:
      labels:
        app: booksstorage-client-depl
    spec:
      containers:
        - name: booksstorage-client
          image:
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: "50m"
              memory: 100Mi
            limits:
              cpu: "150m"
              memory: 256Mi
          ports:
            - containerPort: 80
          volumeMounts:
            - name: booksstorageclient-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: booksstorageclient-config
          configMap:
            name: booksstorageclient-config
      restartPolicy: Always
