apiVersion: v1
data:
  nginx.conf: |
    events {
      worker_connections  1024;
    }

    http {
      include /etc/nginx/mime.types;
      include /etc/nginx/conf.d/*.conf;

      server {
        listen 80;
        server_name booksstorage-svc;
        
        root /usr/share/nginx/html;

        location / {
          proxy_pass http://booksstorage-svc;
          proxy_set_header Host $host;
        }
      }
    }
kind: ConfigMap
metadata:
  name: booksstorageclient-config
