apiVersion: v1
kind: Service
metadata:
  name: booksstorage-client-svc
spec:
  selector:
    app: booksstorage-client-depl
  type: NodePort
  ports:
    - name: booksstorage-client-svc
      protocol: TCP
      port: 80
      targetPort: 80
