apiVersion: apps/v1
kind: Deployment
metadata:
  name: booksstorage-depl
spec:
  template:
    spec:
      containers:
        - name: booksstorage
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "300Mi"
              cpu: "500m"
