apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
    path: 01-image.yaml
  - target:
      kind: Deployment
    path: 03-env.yaml
  - target:
      kind: Deployment
    path: 04-resources.yaml
