apiVersion: apps/v1
kind: Deployment
metadata:
  name: booksstoragefeeder-depl
spec:
  template:
    spec:
      containers:
        - name: booksstoragefeeder
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "300Mi"
              cpu: "300m"
