apiVersion: apps/v1
kind: Deployment
metadata:
  name: booksstorage-mail-depl
spec:
  selector:
    matchLabels:
      app: booksstorage-mail-depl
  template:
    metadata:
      labels:
        app: booksstorage-mail-depl
    spec:
      containers:
        - name: booksstorage-mail
          image: viniciusrw/booksstorage-mail:1.0.3-k8s
          ports:
            - containerPort: 80
              name: apiport
