apiVersion: apps/v1
kind: Deployment
metadata:
  name: booksstorage-mail-depl
spec:
  selector:
    matchLabels:
      app: booksstorage-mail-depl
  template:
    metadata:
      labels:
        app: booksstorage-mail-depl
    spec:
      containers:
      - name: booksstorage-mail
        image: viniciusrw/booksstorage-mail:1.0.3-k8s
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "350Mi"
            cpu: "200m"
        ports:
        - containerPort: 80
          name: apiport
