name: BooksStorage Action

on:
  push:
    branches:
      - main
    paths:
      - "server/booksstorage/**"

jobs:
  build-publish-image:
    uses: ./.github/workflows/build-publish-image.yaml
    secrets: inherit
    with:
      imageName: "booksstorage"
      projectDirectory: "server/booksstorage"

  image-quality:
    uses: ./.github/workflows/image-quality.yaml
    needs: build-publish-image
    secrets: inherit
    with:
      imageName: "booksstorage"
