name: BooksStorage Action

on:
  push:
    branches:
      - "master"
    paths:
      - "server/booksstorage/**"

jobs:
  code-quality:
    uses: ./.github/workflows/code-quality.yaml
    permissions:
      security-events: write

  build-publish-image:
    uses: ./.github/workflows/build-publish-image.yaml
    secrets: inherit
    needs: code-quality
    with:
      imageName: "booksstorage"
      projectDirectory: "server/booksstorage"

  image-quality:
    uses: ./.github/workflows/image-quality.yaml
    needs: build-publish-image
    with:
      imageName: "booksstorage"
