name: BooksStorage-Feeder Action

on:
  push:
    branches:
      - main
    paths:
      - "server/booksstorage-feeder/**"

jobs:

  build-publish-image:
    uses: ./.github/workflows/build-publish-image.yaml
    secrets: inherit
    with:
      imageName: "booksstorage-feeder"
      projectDirectory: "server/booksstorage-feeder"

  image-quality:
    uses: ./.github/workflows/image-quality.yaml
    needs: build-publish-image
    secrets: inherit
    with:
      imageName: "booksstorage-feeder"
