name: Build BooksStorage Image and Push

on:
  push:
    tags:
      - "v*"

jobs:
  build-push-booksstorage-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/booksstorage
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  
      - name: Build and Push Image
        uses: docker/build-push-action@v5.3.0
        with:
          context: server/BooksStorage
          file: server/BooksStorage/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
