name: Build BooksStorage Image and Push

on:
  push:
    branches:
      - "master"
      - "develop"
    paths:
      - "server/BooksStorage/**"

jobs:
  build-push-booksstorage-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Latest Tag
        id: latesttag
        uses: WyriHaximus/github-action-get-previous-tag@v1.4.0
        with:
          fallback: 1.0.0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  
      - name: Build and Push Image
        uses: docker/build-push-action@v5.3.0
        with:
          context: server/BooksStorage
          file: server/BooksStorage/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/booksstorage:latest,${{ secrets.DOCKERHUB_USERNAME }}/booksstorage:${{ steps.latesttag.outputs.tag }}-${{ github.run_number }}
